version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mysql:
    # Prod is 10.1.26
    image: mysql:8.0
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  redis:
    # Prod is 3.2.9
    image: library/redis:5.0.5
    ports:
      - "6379:6379"

volumes:
  data:
  esdata:
